### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by DBraun** [geaxgx/depthai_handface#2]
Wonderful set of OAK-D projects! What's the license for this one? I'd also like to know the licenses for
https://github.com/geaxgx/depthai_movenet and https://github.com/geaxgx/openvino_movenet_multipose

Please add them to the repos when you get a chance. Thanks!

**Comment by geaxgx** [comment]
Consider it is MIT license. 
Can't update repos now but will soon.

**Comment by DBraun** [comment]
Thanks!
